#!/bin/sh

set -e

if [ $# -ne 1 ]
then
  echo 'Usage: init-project PROJECT_NAME'
  exit 1
fi

FOLDER=$1

mkdir $FOLDER
cp .Makefile.template $FOLDER/Makefile
touch $FOLDER/$FOLDER.c
touch $FOLDER/$FOLDER.h
