#!/bin/sh

set -e

if [ $# -ne 1 ]
then
  echo 'Usage: init-project PROJECT_NAME'
  exit 1
fi

FOLDER=$1

mkdir $FOLDER

ln -vs ../Makefile.template $FOLDER/Makefile

touch $FOLDER/$FOLDER.c
echo "
#include \"$FOLDER.h\"

int main()
{

}
" > $FOLDER/$FOLDER.c

touch $FOLDER/$FOLDER.h
echo "

int main(void);
" > $FOLDER/$FOLDER.h

touch $FOLDER/README.md
echo "# $FOLDER\n" > $FOLDER/README.md
